### ISSUE TITLE
Figure out the checksum function

### ISSUE THREAD

**Issue by andreondra** [andreondra/sermatec-inverter#4]
Before this issue is resolved, we cannot reliably send parameter changes to the inverter.

**Comment by andreondra** [comment]
The checksum function does not correspond to the function described in the docs. This will need further investigation. The module reports its hostname as USR-WIFI232-B2 but it seems the protocol is different.

**Comment by mboron** [comment]
@andreondra - It is possible to extract and investigate some code from the Android app:
- Download the [Sermatec_1.7.6_Apkpure.apk](https://d.apkpure.com/b/APK/com.sermatec.inverter?version=latest)
- Rename `Sermatec_1.7.6_Apkpure.apk` to `Sermatec_1.7.6_Apkpure.zip` and unzip it
- Convert `classes.dex` and `classes2.dex` files into `*.jar` files using the `dex-tools`
  - https://stackoverflow.com/questions/1249973/how-to-decompile-dex-into-java-source-code
- Decompile `jar` files to Source code using the [jd-gui](http://jd.benow.ca/) or IntelliJ or similar tools/IDEs.

The problem is that most class names and method names are obfuscated. So one has to have some idea/tips what to search.

**Comment by andreondra** [comment]
Thanks for the tip! There is another tool which can decompile apks directly: https://bytecodeviewer.com/.

Also I've got better results with app version 1.4.2. It's way more readable, probably not obfuscated.

**Comment by andreondra** [comment]
The function has been discovered: xor all bytes until the checksum byte position, then xor with `0x0f` = resulting checksum.
